development:
  adapter: redis
  url: <%= ENV.fetch("SPACEPAL_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Backend_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("SPACEPAL_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Backend_production
